<?php
############################################################
# PODCAST GENERATOR
#
# Created by Alberto Betella
# http://podcastgen.sourceforge.net
# 
# This is Free Software released under the GNU/GPL License.
############################################################

# PG v.1.1

$SL_back = "Back";
$SL_canproceed = "You can proceed with Podcast Generator Installation...";
$SL_catexist = "Categories file already exists...";
$SL_checkolddata = "Looking for existing data generated by an old version of podcast generator...";
$SL_checkperm = "Now checking folders permissions";
$SL_complete = "Installation completed successfully :-)";
$SL_configcreation = "Creation of the configuration file...";
$SL_configdelete = "Please delete this file before proceeding with the installation...";
$SL_configexists = "Config.php file already exists!";
$SL_copyright = "Your copyright notice";
$SL_enteruserandpwd = "Choose a username and a password for the admin page:";
$SL_freeboxcontent = "FREEBOX: in this box you can write freely what you wish: add links, text, HTML code through a visual editor from the admin section! You can optionally disable this feature if you don't need it...";
$SL_freeboxexist = "Freebox text already exists...";
$SL_imgdir = "Images Directory";
$SL_iswritable = "is writable";
$SL_mediadir = "Media Directory";
$SL_next = "Next";
$SL_noolddata = "Nothing to convert.";
$SL_notwritable = "is NOT writable";
$SL_nouser = "You didn't enter the username...";
$SL_permok = "Directories have correct writing permissions";
$SL_permtried = "I tried to set writing permissions (chmod 777) to the directories listed above...";
$SL_pg = "Podcast Generator";
$SL_pgsetup = "- Setup"; 
$SL_podcast_description = "This is the description of your podcast... you can change it trough the administration area.";
$SL_podcast_subtitle = "Subtitle";
$SL_podcast_title = "Podcast Title";
$SL_pwd = "Password:";
$SL_pwdconfirm = "Please type again your password:"; 
$SL_pwdwrong = "You didn't enter a password or the two passwords do not correspond; please go back and type your password again...";
$SL_reload1 = "Reload this page";
$SL_reload2 = "and see if you can proceed with the installation of the script.";
$SL_scriptdir = "Root Directory"; 
$SL_setman = "...if not, set writing permission manually using your FTP program and be sure to have the privilege to change permission to folders on your server.";
$SL_settingchmod = "Setting writing permission to";
$SL_start = "Start managing your podcast!";
$SL_step1 = "First I'll check correct writing permission in the images folder, media folder, and root folder where you installed the script.";
$SL_trytochmod = "Try to set writing permission:";
$SL_uncategorized = "Uncategorized";
$SL_username = "Username:"; 
$SL_welcome = "Welcome!";
$SL_welcometext = "Welcome to the Setup Wizard; just follow the simple steps to install Podcast Generator...";
$SL_yourserv = "Hint: if you are installing Podcast Generator on a Windows server probably you can't assign permissions to files and folders: be sure you installed the script in the correct writable directory (ask to your hosting provider if not sure).";

?>