<?php
############################################################
# PODCAST GENERATOR
#
# Created by Alberto Betella
# http://podcastgen.sourceforge.net
# 
# This is Free Software released under the GNU/GPL License.
############################################################

# PG v.1.1

_("Back") = "Back";
_("You can proceed with Podcast Generator Installation...") = "You can proceed with Podcast Generator Installation...";
_("Categories file already exists...") = "Categories file already exists...";
_("Looking for existing data generated by an old version of podcast generator...") = "Looking for existing data generated by an old version of podcast generator...";
_("Now checking folders permissions") = "Now checking folders permissions";
_("Installation completed successfully :-)") = "Installation completed successfully :-)";
_("Creation of the configuration file...") = "Creation of the configuration file...";
_("Please delete this file before proceeding with the installation...") = "Please delete this file before proceeding with the installation...";
_("Config.php file already exists!") = "Config.php file already exists!";
_("Your copyright notice") = "Your copyright notice";
_("Choose a username and a password for the admin page:") = "Choose a username and a password for the admin page:";
_("FREEBOX: in this box you can write freely what you wish: add links, text, HTML code through a visual editor from the admin section! You can optionally disable this feature if you don't need it...") = "FREEBOX: in this box you can write freely what you wish: add links, text, HTML code through a visual editor from the admin section! You can optionally disable this feature if you don't need it...";
_("Freebox text already exists...") = "Freebox text already exists...";
_("Images Directory") = "Images Directory";
_("is writable") = "is writable";
_("Media Directory") = "Media Directory";
_("Next") = "Next";
_("Nothing to convert.") = "Nothing to convert.";
_("is NOT writable") = "is NOT writable";
_("You didn't enter the username...") = "You didn't enter the username...";
_("Directories have correct writing permissions") = "Directories have correct writing permissions";
$SL_permtried = "I tried to set writing permissions (chmod 777) to the directories listed above...";
$SL_pg = "Podcast Generator";
_("- Setup") = "- Setup"; 
_("This is the description of your podcast... you can change it through the administration area.") = "This is the description of your podcast... you can change it through the administration area.";
_("Subtitle") = "Subtitle";
_("Podcast Title") = "Podcast Title";
_("Password:") = "Password:";
_("Please type again your password:") = "Please type again your password:"; 
_("You didn't enter a password or the two passwords do not correspond; please go back and type your password again...") = "You didn't enter a password or the two passwords do not correspond; please go back and type your password again...";
_("Reload this page") = "Reload this page";
_("and see if you can proceed with the installation of the script.") = "and see if you can proceed with the installation of the script.";
_("Root Directory") = "Root Directory"; 
_("...if not, set writing permission manually using your FTP program and be sure to have the privilege to change permission to folders on your server.") = "...if not, set writing permission manually using your FTP program and be sure to have the privilege to change permission to folders on your server.";
_("Setting writing permission to") = "Setting writing permission to";
_("Start managing your podcast!") = "Start managing your podcast!";
_("First I'll check correct writing permission in the images folder, media folder, and root folder where you installed the script.") = "First I'll check correct writing permission in the images folder, media folder, and root folder where you installed the script.";
_("Try to set writing permission:") = "Try to set writing permission:";
_("Uncategorized") = "Uncategorized";
_("Username") = "Username:"; 
_("Welcome!") = "Welcome!";
_("Welcome to the Setup Wizard; just follow the simple steps to install Podcast Generator...") = "Welcome to the Setup Wizard; just follow the simple steps to install Podcast Generator...";
_("Hint: if you are installing Podcast Generator on a Windows server probably you can't assign permissions to files and folders: be sure you installed the script in the correct writable directory (ask to your hosting provider if not sure).") = "Hint: if you are installing Podcast Generator on a Windows server probably you can't assign permissions to files and folders: be sure you installed the script in the correct writable directory (ask to your hosting provider if not sure).";

?>