<?php
############################################################
# PODCAST GENERATOR
#
# Created by Alberto Betella
# http://podcastgen.sourceforge.net
# 
# This is Free Software released under the GNU/GPL License.
############################################################

include ('checkconfigexistence.php');
?>


	<ul class="episode_imgdesc">
	<li>

	<?php

$PG_mainbody = NULL; //define

$PG_mainbody .= '<p>'._("Looking for existing data generated by an old version of podcast generator...").'</p>';

include ('upgrade.php'); //check for data generated by an old version (0.8 or 0.9x) of podcast generator, and convert it

if (!isset($oldepisodesfound)) {

	$PG_mainbody .= '<p><b>'._("Nothing to convert.").'</b></p>';

}


$PG_mainbody .= '<br /><p><b>'._("Now checking folders permissions").'</b></p><p>'._("First I'll check correct writing permission in the images folder, media folder, and root folder where you installed the script.").'</p>
	<form method="post" action="index.php?step=3">
	<br />
	<input type="hidden" name="setuplanguage" value="'.$_POST['setuplanguage'].'">
	<input type="submit" value="'._("Next").'">
	</form>
	';


//print output

echo $PG_mainbody;

?>


	</li>
	</ul>