<?php
############################################################
# PODCAST GENERATOR
#
# Created by Alberto Betella
# http://podcastgen.sourceforge.net
# 
# This is Free Software released under the GNU/GPL License.
############################################################

include ('checkconfigexistence.php');
?>


	<ul class="episode_imgdesc">
	<li>

	<?php

$PG_mainbody = NULL; //define

$PG_mainbody .= '<p>'.$SL_checkolddata.'</p>';

include ('upgrade.php'); //check for data generated by an old version (0.8 or 0.9x) of podcast generator, and convert it

if (!isset($oldepisodesfound)) {

	$PG_mainbody .= '<p><b>'.$SL_noolddata.'</b></p>';

}


$PG_mainbody .= '<br /><p><b>'.$SL_checkperm.'</b></p><p>'.$SL_step1.'</p>
	<form method="post" action="index.php?step=3">
	<br />
	<input type="hidden" name="setuplanguage" value="'.$_POST['setuplanguage'].'">
	<input type="submit" value="'.$SL_next.'">
	</form>
	';


//print output

echo $PG_mainbody;

?>


	</li>
	</ul>